### ISSUE TITLE
TestPackStreamingPerformance: Expected to write 1000 objects into pack, but received only 0 from iterators

### ISSUE THREAD

**Issue by ignatenkobrain** [gitpython-developers/smmap#34] opened 2016-12-28 11:40 UTC
```
ERROR: test_pack_writing (gitdb.test.performance.test_pack_streaming.TestPackStreamingPerformance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brain/git/fedora/python-gitdb/gitdb-2.0.0/gitdb/test/lib.py", line 72, in wrapper
    return func(self, *args, **kwargs)
  File "/home/brain/git/fedora/python-gitdb/gitdb-2.0.0/gitdb/test/performance/test_pack_streaming.py", line 58, in test_pack_writing
    PackEntity.write_pack((pdb.stream(sha) for sha in pdb.sha_iter()), ostream.write, object_count=ni)
  File "/home/brain/git/fedora/python-gitdb/gitdb-2.0.0/gitdb/pack.py", line 980, in write_pack
    "Expected to write %i objects into pack, but received only %i from iterators" % (object_count, actual_count))
ValueError: Expected to write 1000 objects into pack, but received only 0 from iterators
-------------------- >> begin captured logging << --------------------
root: INFO: You can set the GITDB_TEST_GIT_REPO_BASE environment variable to a .git repository of your choice - defaulting to the gitdb repository
--------------------- >> end captured logging << ---------------------
```

**Comment by Byron** [comment] 2017-01-21 15:05
I am unable to reproduce the issue, and here is what I did:
```bash
git clone https://github.com/gitpython-developers/gitdb
git submodule update --init --recursive
nosetests gitdb/test/performance
```

Which outputs:
```
Endurance run: verify streaming of objects (crc and sha)
PDB: verified 2222 objects (crc=0) in 0.475554 s ( 4672.445294 objects/s )
PDB: verified 2222 objects (crc=1) in 0.024003 s ( 92571.650522 objects/s )
.Verified 1000 loose object compression/decompression cycles
Verified 2000 loose object compression/decompression cycles
.PDB: looked up 2222 shas by index in 0.001660 s ( 1338658.932491 shas/s )
PDB: looked up 2222 sha in 1 packs in 0.007448 s ( 298336.806172 shas/s )
PDB: Obtained 10000 object INFO by sha in 0.106737 s ( 93688.104215 items/s )
PDB: Obtained 10000 object STREAM by sha in 0.147985 s ( 67574.424757 items/s )
PDB: Obtained 5000 streams by sha and read all bytes totallying 9799 KiB ( 24521.522803 KiB / s ) in 0.399608 s ( 12512.257783 streams/s )
.PDB Streaming: Got 1000 streams by sha in in 0.039038 s ( 25616.103874 streams/s )
..Creating  data ...
Done (in 1.289086 s)
Added 50000 KiB (filesize = 17294 KiB) of  data to loose odb in 0.905660 s ( 55208.361578 Write KiB / s)
Read 50000 KiB of  data at once from loose odb in 0.222715 s ( 224502.266270 Read KiB / s)
Read 50000 KiB of  data in 512 KiB chunks from loose odb in 0.201186 s ( 248526.311423 Read KiB / s)
Creating random  data ...
Done (in 9.469834 s)
Added 50000 KiB (filesize = 43183 KiB) of random  data to loose odb in 1.863079 s ( 26837.293584 Write KiB / s)
Read 50000 KiB of random  data at once from loose odb in 0.337923 s ( 147962.679701 Read KiB / s)
Read 50000 KiB of random  data in 512 KiB chunks from loose odb in 0.312093 s ( 160208.645751 Read KiB / s)
.
----------------------------------------------------------------------
Ran 6 tests in 17.455s

OK
```

I am closing this issue for now, but please feel free to provide instructions to help reproducing the issue.

**Closed by Byron** 2017-01-21 15:05 UTC
